// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: protoc/http_greeter/http_greeter.proto

/*
Package http_greeter is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package http_greeter

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/descriptor"
	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = descriptor.ForMessage

func request_GreeterHTTPAPI_Say_0(ctx context.Context, marshaler runtime.Marshaler, client GreeterHTTPAPIClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq HttpRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.Say(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_GreeterHTTPAPI_Say_0(ctx context.Context, marshaler runtime.Marshaler, server GreeterHTTPAPIServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq HttpRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.Say(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterGreeterHTTPAPIHandlerServer registers the http handlers for service GreeterHTTPAPI to "mux".
// UnaryRPC     :call GreeterHTTPAPIServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
func RegisterGreeterHTTPAPIHandlerServer(ctx context.Context, mux *runtime.ServeMux, server GreeterHTTPAPIServer) error {

	mux.Handle("POST", pattern_GreeterHTTPAPI_Say_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_GreeterHTTPAPI_Say_0(rctx, inboundMarshaler, server, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GreeterHTTPAPI_Say_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterGreeterHTTPAPIHandlerFromEndpoint is same as RegisterGreeterHTTPAPIHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterGreeterHTTPAPIHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterGreeterHTTPAPIHandler(ctx, mux, conn)
}

// RegisterGreeterHTTPAPIHandler registers the http handlers for service GreeterHTTPAPI to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterGreeterHTTPAPIHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterGreeterHTTPAPIHandlerClient(ctx, mux, NewGreeterHTTPAPIClient(conn))
}

// RegisterGreeterHTTPAPIHandlerClient registers the http handlers for service GreeterHTTPAPI
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "GreeterHTTPAPIClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "GreeterHTTPAPIClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "GreeterHTTPAPIClient" to call the correct interceptors.
func RegisterGreeterHTTPAPIHandlerClient(ctx context.Context, mux *runtime.ServeMux, client GreeterHTTPAPIClient) error {

	mux.Handle("POST", pattern_GreeterHTTPAPI_Say_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_GreeterHTTPAPI_Say_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GreeterHTTPAPI_Say_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_GreeterHTTPAPI_Say_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0}, []string{"say"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_GreeterHTTPAPI_Say_0 = runtime.ForwardResponseMessage
)
